### ISSUE TITLE
Create Login User Interface

### ISSUE THREAD

**Issue by Salazar2893** [jackyhuynh/OrangeFrontend#2]
## As a Developer:
- I want to see a Login user interface.
        - Username Field / Password Field
        - Alternative Login Methods

## So that I can:
- Have a platform for users to login to.

## Accepting:
- Base level allowing to view Login" Username/Password/Alt Methods.

**Comment by jackyhuynh** [comment]
Take a look at the [MUI component](https://mui.com/material-ui/getting-started/templates/) and see all the free Login Template overthere.

**Comment by Salazar2893** [comment]
Utilized MUI Login template to create a Login User page and verified its operating on multiple operating systems.
